server:
  port: 16666

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql:///wechat1810
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
fdfs:
  connect-timeout: 6000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 80
    height: 80
  tracker-list:
    - 47.112.207.98:22122